export let easy = [
  "anode", "apple", "book", "cat", "dog", "elephant", "fish", "grape", "hat", "ice", "joke",
  "kite", "lamp", "moon", "nest", "orange", "pear", "queen", "river", "sun", "tree",
  "umbrella", "vase", "wolf", "python", "yarn", "zebra", "broom", "cloud", "dew",
  "egg", "fan", "glove", "horse", "iron", "jelly", "key", "lion", "map", "nut", "owl",
  "plum", "quiz", "rose", "star", "tiger", "urn", "violin", "wax", "yak", "zip", "ball",
  "chair", "door", "ear", "frog", "guitar", "hammer", "igloo", "jug", "kangaroo", "leaf",
  "able", "about", "above", "act", "add", "after", "again", "age", "ago",
  "air", "all", "also", "am", "among", "an", "and", "any", "are", "as",
  "ask", "at", "back", "bad", "be", "been", "big", "but", "by", "call",
  "can", "car", "care", "case", "cause", "child", "city", "clear", "close",
  "cold", "come", "could", "cut", "day", "did", "do", "does", "done", "down",
  "each", "early", "earth", "east", "easy", "eat", "end", "even", "ever", "eye",
  "face", "fact", "fall", "far", "feel", "few", "find", "fine", "fire", "first",
  "five", "for", "form", "found", "four", "from", "full", "get", "give", "go",
  "good", "got", "great", "had", "hand", "has", "have", "he", "head", "hear",
  "heat", "help", "her", "here", "high", "him", "his", "home", "hot", "hour",
  "how", "I", "idea", "if", "in", "into", "is", "it", "its", "just",
  "bounce", "brush", "bury", "carry", "cheer", "clap", "compete", "confuse",
  "copy", "crawl", "decide", "delay", "deliver", "deny", "destroy", "develop",
  "divide", "doubt", "drag", "drip", "employ", "encourage", "enjoy", "expand",
  "keep", "kind", "know", "land", "large", "last", "late", "lead", "learn", "leave",
  "left", "less", "let", "life", "light", "like", "line", "list", "little", "live",
  "long", "look", "love", "made", "make", "man", "many", "may", "me", "mean",
  "men", "might", "mile", "miss", "more", "most", "move", "much", "must", "my",
  "name", "near", "need", "never", "new", "next", "night", "no", "not", "now",
  "of", "off", "often", "old", "on", "once", "one", "only", "or", "other",
  "our", "out", "over", "own", "page", "part", "pay", "per", "play", "point",
  "put", "quick", "read", "real", "right", "run", "said", "same", "saw", "say",
  "school", "sea", "see", "seem", "self", "set", "she", "should", "show", "side",
  "since", "six", "small", "so", "some", "soon", "sound", "still", "such", "take",
  "tell", "ten", "than", "that", "the", "their", "them", "then", "there", "these",
  "they", "think", "this", "three", "time", "to", "too", "took", "true", "try",
  "turn", "two", "under", "up", "us", "use", "very", "want", "was", "water",
  "way", "we", "week", "well", "went", "were", "what", "when", "where", "which",
  "while", "white", "who", "why", "will", "with", "word", "work", "world", "would",
  "write", "year", "you", "young", "your", "acid", "ago", "agree", "ahead",
  "air", "allow", "alone", "along", "also", "anger", "angle", "angry", "animal",
  "answer", "any", "apple", "arm", "army", "around", "arrive", "art", "ask", "at",
  "atom", "away", "baby", "back", "bad", "bag", "ball", "band", "bank", "bar",
  "base", "bath", "be", "bean", "bear", "beat", "bed", "bell", "bend", "bent",
  "best", "bet", "better", "between", "beyond", "big", "bill", "bind", "bird",
  "birth", "bit", "bite", "black", "blade", "bleed", "blend", "bless", "blind",
  "block", "blood", "blow", "blue", "board", "boat", "body", "bolt", "bomb",
  "bone", "book", "boot", "born", "both", "bottle", "bottom", "bound", "bow",
  "box", "boy", "brain", "brake", "branch", "brand", "bread", "break", "breath",
  "breeze", "brick", "bridge", "brief", "bright", "bring", "broad", "broke",
  "brown", "brush", "buck", "bud", "bug", "build", "bulk", "bull", "bump",
  "burn", "burst", "bus", "busy", "but", "buy", "by",
  "cage", "cake", "call", "camp", "card", "care", "carp", "cart", "case", "cash",
  "cast", "cat", "cave", "cell", "cent", "chain", "chair", "chalk", "chance",
  "change", "charge", "chart", "chase", "chat", "check", "cheese", "cherry", "chest",
  "chew", "chick", "child", "chip", "chocolate", "choice", "choir", "church", "circle",
  "claim", "clap", "class", "claw", "clay", "clean", "clear", "climb", "clip",
  "clock", "close", "cloth", "cloud", "club", "clue", "cluster", "coach", "coal",
  "coat", "code", "coffee", "coil", "coin", "cold", "collar", "collect", "color",
  "column", "comb", "come", "comfort", "command", "comment", "common", "company",
  "compare", "compass", "complete", "complex", "component", "compose", "compound", "comprehend",
  "compress", "compromise", "compute", "concentrate", "concept", "concern", "concert", "conclude",
  "condition", "conduct", "confess", "confide", "configure", "confirm", "conflict", "conform",
  "confront", "confuse", "congratulate", "connect", "conquer", "conscience", "conscious", "consent",
  "consequence", "consider", "consist", "console", "conspire", "constant", "construct", "consult",
  "consume", "contact", "contain", "contaminate", "contemplate", "contest", "context", "continue",
  "contract", "contradict", "contrast", "contribute", "control", "converse", "convert", "convict",
  "convince", "cook", "cool", "cooperate", "coordinate", "cope", "copy", "core", "corner",
  "correct", "correlate", "correspond", "corrupt", "cost", "cotton", "couch", "cough", "count",
  "country", "couple ", "course", "court", "cousin", "cover", "cow", "crack", "craft",
  "crane", "crash", "crawl", "crazy", "cream", "create", "credit", "creep", "crew",
  "crime", "crimson", "critic", "criticize", "crop", "cross", "crow", "crowd", "crown",
  "crush", "cry", "crypt", "cube", "cubic", "cue", "cuff", "cuisine", "cultivate",
  "culture", "cup", "cupboard", "curb", "cure", "curl", "curly", "current", "curse",
  "curve", "cushion", "custom", "cut", "cycle", "cylinder", "dagger", "daily", "dairy",
  "dance", "danger", "dare", "dark", "dart", "dash", "data", "date", "daughter",
  "dawn", "day", "deal", "dean", "dear", "death", "debate", "debt", "decay", "deceit",
  "decide", "deck", "declare", "decorate", "deduce", "deed", "deep", "deer", "defeat",
  "defect", "defend", "define", "defy", "degree", "delay", "delete", "delight", "deliver",
  "demand", "demolish", "denial", "denounce", "dent", "deny", "depart", "depend", "deposit",
  "depress", "depth", "derive", "descend", "describe", "desert", "design", "desire", "despair",
  "destroy", "detail", "detect", "deter", "develop", "device", "devise", "devote", "dew",
  "diagram", "dial", "diamond", "diaper", "dictate", "die", "diet", "differ", "difficult",
  "diffuse", "digest", "digital", "dilemma", "dine", "dinner", "dip", "direct", "directory",
  "dirt", "dirty", "disagree", "disappear", "disaster", "disc", "discard", "discern", "discharge",
  "discipline", "disclose", "discount", "discourage", "discuss", "disease", "dish", "dismiss",
  "disorder", "display", "displease", "dispose", "dispute", "dissolve", "distance", "distinct",
  "distribute", "district", "distrust", "diverge", "diversity", "divide", "divine", "divorce",
  "dizzy", "dock", "doctor", "document", "dog", "dollar", "dome", "domestic", "donate",
  "door", "dose", "dot", "double", "dough", "dove", "down", "dozen", "draft", "drag",
  "dragon", "draw", "dream", "dress", "drift", "drill", "drink", "drive", "drop",
  "drought", "drown", "drum", "dry", "duck", "dull", "dumb", "dump", "dune", "dusk",
  "dust", "duty", "dwarf", "dwell", "dwindle", "dye", "dying", "each", "eagle", "ear",
  "earth", "ease", "east", "easy", "eat", "echo", "ecstasy", "edge", "edit", "educate",
  "effect", "effort", "egg", "ego", "eight", "either", "elbow", "elect", "element",
  "elevate", "elf", "elicit", "eliminate", "elite", "else", "embark", "embody", "emerge",
  "emotion", "empathy", "empire", "employ", "empty", "enable", "encourage", "end", "endure",
  "energy", "enforce", "engage", "engine", "enhance", "enjoy", "enlarge", "enlighten", "enlist",
  "enough", "enquire", "ensure", "enter", "entertain", "entire", "entity", "entrance", "entry",
  "envelope", "envy", "episode", "equal", "equation", "equip", "era", "erect", "erode",
  "err", "error", "escape", "essay", "establish", "estate", "estimate", "eternal", "ethic",
  "euphoria", "evade", "evaluate", "even", "event", "ever", "every", "evidence", "evil",
  "evolve", "exact", "exaggerate", "examine", "example", "excess", "exchange", "excite", "exclaim",
  "exclude", "excuse", "execute", "exempt", "exercise", "exhaust", "exhibit", "exile", "exist",
  "exit", "exodus", "expand", "expect", "expel", "expense", "experience", "experiment", "expert",
  "expire", "explain", "explode", "exploit", "explore", "export", "expose", "express", "extend",
  "extinct", "extreme", "eye", "eyebrow", "face", "fact", "factor", "factory", "faculty",
  "fade", "fail", "faint", "fair", "faith", "fall", "false", "fame", "family", "famous",
  "fan", "fancy", "fantasy", "far", "fare", "farm", "fashion", "fast", "fat", "fate",
  "father", "fault", "favor", "fear", "feast", "feather", "feature", "federal", "fee",
  "feed", "feel", "feet", "fell", "fellow", "felt", "female", "fence", "ferry", "fertile",
  "festival", "fetch", "fever", "few", "fiber", "fiction", "field", "fierce", "fifteen",
  "fifth", "fifty", "fight", "figure", "file", "fill", "film", "filter", "final",
  "finance", "find", "fine", "finger", "finish", "fire", "firm", "first", "fish",
  "fist", "fit", "five", "fix", "flag", "flame", "flash", "flat", "flavor", "flea",
  "flesh", "flex", "flick", "flight", "flip", "float", "flock", "floor", "flour", "flow",
  "flower", "flute", "fly", "foam", "focus", "fog", "fold", "folk", "follow", "food",
  "fool", "foot", "football", "for", "force", "forecast", "forehead", "forest", "forever",
  "forgive", "fork", "form", "formal", "format", "former", "formula", "forth", "fortress",
  "fortune", "forward", "fossil", "foster", "found", "foundation", "four", "fox", "fraction",
  "fragile", "frame", "frank", "fraud", "free", "freedom", "freeze", "french", "frequent",
  "fresh", "friction", "friend", "fright", "fringe", "frog", "from", "front", "frost",
  "frown", "fruit", "fuel", "full", "fun", "function", "fund", "funeral", "fungus", "fur",
  "furnace", "furniture", "fury", "fuse", "fusion", "future", "gadget", "gain", "galaxy",
  "gale", "gall", "game", "gang", "gap", "garage", "garden", "garlic", "gas", "gate",
  "gather", "gauge", "gaze", "gear", "gem", "general", "generate", "genius", "genre",
  "gentle", "genuine", "geography", "geometry", "germ", "gesture", "get", "ghost", "giant",
  "gift", "giggle", "girl", "give", "glad", "glance", "glare", "glass", "glide", "glitter",
  "globe", "glory", "glove", "glow", "goal", "goat", "god", "gold", " golf", "good",
  "goose", "gorge", "gospel", "gossip", "govern", "government", "gown", "grab", "grace",
  "grade", "gradual", "graduate", "grain", "grand", "grant", "graph", "grape", "graphite", "grass",
  "grate", "grave", "gravity", "gray", "great", "green", "greet", "grey", "grid", "grief",
  "grill", "grim", "grin", "grip", "groan", "groove", "gross", "ground", "group", "grow",
  "growl", "growth", "grudge", "grumble", "grunt", "guarantee", "guard", "guess", "guest", "guide",
  "guilt", "guilty", "gulf", "gulp", "gun", "gust", "gut", "guy", "gym", "gymnast", "gypsy",
  "habit", "hail", "hair", "half", "hall", "halt", "ham", "hammer", "hand", "handful", "handy",
  "hang", "happen", "happy", "harbor", "hard", "harm", "harmony", "harp", "harsh", "haste",
  "hat", "hate", "haul", "have", "hawk", "hay", "hazard", "head", "heal", "health", "heap",
  "hear", "heart", "heat", "heaven", "heavy", "hedge", "heel", "height", "helmet", "help",
  "hem", "herd", "here", "hero", "heroin", "hers", "hesitate", "hide", "high", "highlight",
  "highway", "hill", "hint", "hip", "hire", "his", "history", "hit", "hive", "hoax", "hobby",
  "hold", "hole", "holiday", "hollow", "holly", "home", "honey", "hood", "hook", "hop",
  "hope", "horn", "horror", "horse", "host", "hostile", "hot", "hotel", "hour", "house",
  "household", "hug", "huge", "human", "humble", "humid", "humor", "hundred", "hungry", "hunt",
  "hurdle", "hurl", "hurt", "husband", "hut", "hybrid", "hydrogen", "hype", "hypnotic", "hypothesis",
  "ice", "iceberg", "icon", "idea", "ideal", "identical", "identify", "identity", "idle", "ignition",
  "ignore", "ill", "illegal", "illness", "illusion", "image", "imagine", "imitate", "immense", "immune",
  "impact", "impatient", "impede", "impel", "imply", "import", "impose", "impossible", "impress", "improve",
  "incentive", "inch", "incident", "include", "income", "increase", "incubate", "incur", "indeed", "indefinite",
  "independence", "independent", "index", "indicate", "indifferent", "indoor", "induce", "indulge", "industry", "inevitable",
  "infect", "infer", "inflict", "influence", "inform", "infuse", "ingredient", "inhabit", "inherit", "inhibit",
  "initial", "initiate", "inject", "injure", "injustice", "ink", "inmate", "inner", "innocent", "inquire",
  "insane", "inscribe", "insect", "insert", "inside", "insight", "insist", "inspect", "inspire", "install",
  "instance", "instant", "instead", "instinct", "institute", "instruction", "instrument", "insult", "insurance", "intact",
  "integrate", "intend", "intense", "intent", "interact", "interest", "interface", "interior", "intermediate", "internal",
  "international", "internet", "interpret", "interrupt", "interview", "intimate", "into", "introduce", "intrude", "invade",
  "invalid", "invent", "invest", "investigate", "involve", "inward ", "iron", "island", "isolate", "issue",
  "item", "itself", "jacket", "jag", "jail", "jet", "jewel", "join", "joke", "journey", "joy",
  "judge", "juice", "jump", "jungle", "junior", "junk", "just", "kangaroo", "keen", "keep",
  "kettle", "key", "kick", "kid", "kidney", "kind", "king", "kiss", "kit", "kitchen", "kite",
  "kitten", "kiwi", "knee", "knife", "knit", "knob", "know", "label", "labor", "lab", "ladder",
  "lady", "lake", "lamp", "language", "laptop", "large", "later", "latin", "laugh", "laundry",
  "law", "lawn", "lawsuit", "layer", "lazy", "lead", "leaf", "leak", "learn", "lease",
  "leather", "leave", "lecture", "left", "leg", "legal", "legend", "leisure", "lemon", "lend",
  "length", "lens", "leopard", "less", "lesson", "letter", "level", "liar", "liberty", "library",
  "license", "life", "lift", "light", "like", "limb", "limit", "link", "lion", "liquid",
  "list", "little", "live", "load", "loan", "lobster", "local", "lock", "logic", "lonely",
  "long", "loop", "loose", "lord", "lose", "lost", "lot", "loud", "lounge", "love",
  "low", "loyal", "luck", "luggage", "lumber", "lunar", "lunch", "luxury", "lyrics", "machine",
  "mad", "magic", "magnet", "maid", "mail", "main", "major", "make", "mammal", "man",
  "manage", "mandate", "mango", "mansion", "manual", "maple", "marble", "march", "margin",
  "marine", "market", "marriage", "mask", "mass", "master", "match", "material", "math",
  "matrix", "matter", "maximum", "maze", "meadow", "mean", "measure", "meat", "mechanic", "medal",
  "media", "melody", "melt", "member", "memory", "mention", "menu", "mercy", "merge", "merit",
  "merry", "mesh", "message", "metal", "method", "middle", "midnight", "milk", "million", "mimic",
  "mind", "minimum", "minor", "minute", "miracle", "mirror", "misery", "miss", "mistake", "mix",
  "mixed", "mixture", "mobile", "model", "modify", "mom", "moment", "monitor", "monkey", "month",
  "moon", "moral", "more", "morning", "mosquito", "mother", "motion", "motor", "mountain", "mouse",
  "move", "movie", "much", "muffin", "mule", "multiply", "muscle", "museum", "mushroom", "music",
  "must", "mutual", "myself", "mystery", "myth", "naive", "name", "napkin", "narrow", "nasty",
  "nation", "nature", "near", "neck", "need", "negative", "neglect", "neither", "nephew", "nerve",
  "nest", "net", "network", "neutral", "never", "news", "next", "nice", "night", "noise",
  "nominee", "noodle", "normal", "north", "nose", "note", "notebook", "nothing", "notice", "noun",
  "novel", "now", "nuclear", "number", "nun", "nurse", "nut", "oak", "oath", "obey",
  "object", "oblige", "observe", "obtain", "obvious", "occasion", "ocean", "octave", "odd", "odds",
  "offend", "offer", "office", "officer", "official", "often", "oil", "okay", "old", "olive",
  "omen", "omit", "once", "one", "onion", "online", "only", "onto", "open", "operate",
  "opinion", "opponent", "oppose", "opposite", "opt", "optimist", "option", "orange", "orbit", "orchestra",
  "order", "ordinary", "organ", "organize", "orient", "origin", "original", "ornament", "other", "our",
  "outdoor", "outer", "outlet", "outline", "output", "outside", "outstanding", "oven", "over", "overcome",
  "overload", "overnight", "oversee", "overtake", "overtime", "owe", "owl", "own", "owner", "ox",
  "oxygen", "oyster", "pace", "pack", "package", "page", "pain", "paint", "pair", "palace",
  "pale", "palm", "pan", "pancake", "panel", "panic", "panorama", "pant", "paper", "parade",
  "parcel", "pardon", "parent", "park", "parrot", "part", "participate", "particle", "partner", "party",
  "pass", "passage", "passenger", "passport", "password", "paste", "patch", "path", "patience", "patient",
  "patriot", "patrol", "pattern", "pause", "pave", "paw", "pay", "payment", "peace", "peach",
  "peak", "pearl", "peasant", "pebble", "peck", "pedal", "pedestrian", "peek", "peel", "peep",
  "peer", "pen", "penalty", "pencil", "pendant", "penetrate", "pension", "people", "pepper", "perch",
  "percent", "perfection", "perform", "perfume", "perhaps", "period", "perish", "perk", "permanent", "permit",
  "perplex", "persecute", "persist", "person", "persuade", "pertinent", "peruse", "pervade", "perverse", "pesky",
  "petal", "petition", "petty", "phase", "phenomenon", "philosophy", "phone", "photo", "phrase", "physical",
  "piano", "pick", "picture", "piece", "pierce", "pig", "pigeon", "pile", "pill", "pilot",
  "pin", "pinch", "pine", "pink", "pint", "pioneer", "pipe", "pistol", "pit", "pitch",
  "pity", "place", "plague", "plain", "plan", "plane", "planet", "plank", "plant", "plaster",
  "plate", "platform", "platinum", "play", "playground", "plea", "please", "pleasure", "plight", "plot",
  "plow", "pluck", "plug", "plum", "plunge", "poem", "poet", "poetry", "point", "poison",
  "poke", "polar", "pole", "police", "policy", "polish", "polite", "poll", "pollute", "pond",
  "pony", "pool", "poor", "pop", "popcorn", "pope", "popular", "population", "porch", "pore",
  "pork", "porous", "port", "portal", "pose", "position", "positive", "possess", "possible", "post",
  "postage", "postpone", "pot", "potato", "potential", "pouch", "pound", "pour", "poverty", "powder",
  "power", "practice", "praise", "pray", "preach", "precaution", "precede", "precise ", "predict", "prefer",
  "prepare", "prescribe", "present", "preserve", "press", "pressure", "pretend", "pretty", "prevail", "prevent",
  "preview", "price", "pride", "priest", "primary", "prime", "primitive", "prince", "princess", "print",
  "prior", "prison", "private", "prize", "problem", "proceed", "process", "proclaim", "produce", "product",
  "profess", "professor", "profile", "profit", "program", "progress", "prohibit", "project", "prolong", "prominent",
  "promise", "promote", "prompt", "proof", "prop", "propagate", "propel", "proper", "property", "prophet",
  "proportion", "propose", "prospect", "protect", "protein", "protest", "proud", "prove", "provide", "province",
  "provoke", "prowl", "proxy", "prune", "psychic", "public", "publish", "pudding", "puddle", "puff",
  "pull", "pulp", "pulse", "pump", "punch", "punish", "pupil", "puppet", "purchase", "pure",
  "purge", "purple", "purpose", "pursue", "push", "put", "puzzle", "pyramid", "quaint", "quality",
  "quantify", "quantity", "quarrel", "quart", "quarter", "quartz", "queen", "quest", "question", "queue",
  "quick", "quiet", "quill", "quilt", "quit", "quite", "quiver", "quote", "rabbit", "raccoon",
  "race", "rack", "radar", "radio", "radius", "rage", "raid", "rail", "rain", "rainbow",
  "raise", "rake", "rally", "ram", "ranch", "random", "range", "rank", "rapid", "rare",
  "rate", "ratio", "rave", "raw", "ray", "react", "read", "ready", "real", "reality",
  "realize", "rear", "reason", "rebel", "rebound", "recall", "receive", "recent", "recess", "recipe",
  "record", "reduce", "reflect", "reform", "refrain", "refresh", "refuel", "regain", "regard", "regiment",
  "register", "regular", "regulate", "reign", "reject", "relate", "relax", "release", "relevant", "reliable",
  "relief", "relieve", "religion", "relish", "remain", "remark", "remedy", "remember", "remind", "remote",
  "remove", "render", "renew", "rent", "repair", "repeat", "replace", "reply", "report", "represent",
  "request", "require", "rescue", "research", "reside", "resign", "resist", "resource", "respect", "respond",
  "response", "rest", "restore", "result", "resume", "retail", "retain", "retire", "retreat", "return",
  "reveal", "revenge", "revenue", "reverse", "review", "revise", "revive", "reward", "rhythm", "rib",
  "ribbon", "rice", "rich", "ride", "ridge", "rifle", "right", "rigid", "ring", "riot",
  "rip", "ripe", "rise", "risk", "rite", "rival", "river", "road", "roam", "roar",
  "roast", "rob", "robe", "robot", "rock", "rocket", "rod", "role", "roll", "roof",
  "room", "roost", "root", "rope", "rose", "rot", "rotate", "rough", "round", "route",
  "routine", "row", "royal", "rub", "rubber", "rude", "rug", "rule", "ruler", "rum",
  "rumor", "run", "rung", "runner", "rural", "rush", "rust", "rut", "sack", "sad",
  "safe", "sail", "saint", "sale", "salmon", "salt", "same", "sample", "sand", "sane",
  "sap", "sarcasm", "satellite", "sauce", "sausage", "save", "saw", "say", "scale", "scandal",
  "scan", "scar", "scare", "scene", "scheme", "school", "science", "scissors", "score", "scout",
  "scramble", "scrap", "scratch", "scream", "screen", "script", "scroll", "scrub", "sea", "seal",
  "search", "season", "seat", "second", "secret", "section", "sector", "secure", "see", "seed",
  "seek", "seem", "seen", "seize", "select", "self", "sell", "send", "sense", "sensitive",
  "sentence", "separate", "sequence", "series", "serious", "servant", "serve", "service", "session", "set",
  "settle", "setup", "seven", "several", "sew", "sex", "shade", "shadow", "shake", "shall",
  "shallow", "shame", "shape", "share", "shark", "sharp", "shave", "shawl", "she", "shed",
  "sheep", "sheet", "shelf", "shell", "shelter", "shield", "shift", "shine", "shiny", "ship",
  "shirt", "shoe", "shoot", "shop", "shore", "short", "shot", "should", "shoulder", "shout",
  "show", "shower", "shred", "shrimp", "shrine", "shrink", "shroud", "shrub", "shrug", "shut",
  "shutter", "shy", "sick", "side", "sieve", "sight", "sign", "signal", "signature", "signify",
  "silence", "silent", "silk", "silly", "silver", "similar", "simple", "since", "sing", "singer",
  "single", "sink", "sinner", "sip", "sir", "sister", "sit", "site", "situation", "size",
  "skate", "sketch", "ski", "skill", "skin", "skirt", "skull", "sky", "slab", "slam",
  "slant", "slap", "slash", "slate", "slave", "slay", "sleep", "sleeve", "slender", "slice",
  "slide", "slight", "slim", "slip", "slipper", "slope", "slot", "slow", "slush", "small",
  "smart", "smell", "smile", "smoke", "smooth", "snake", "snap", "snare", "snatch", "sneak",
  "sneaker", "sneeze", "sniff", "snob", "snooker", "snoop", "snow", "snowflake", "snug", "soak",
  "soap", "soar", "sob", "sober", "sock", "soda", "sofa", "soft", "software", "soil",
  "solar", "sold", "soldier", "sole", "solid", "solution", "solve", "some", "someone", "something",
  "somewhere", "son", "song", "soon", "soothe", "sophisticated", "sore", "sorry", "sort", "soul",
  "sound", "soup", "source", "south", "space", "spade", "span", "spar", "spare", "spark",
  "sparkle", "sparrow", "spasm", "spat", "spawn", "speak", "speaker", "spear", "special", "species",
  "specific", "spectacle", "speed", "spell", "spend", "sphere", "spice", "spider", "spike", "spill",
  "spin", "spine", "spirit", "spite", "splash", "split", "spoil", "spoke", "sponsor", "spoon",
  "sport", "spot", "spray", "spread", "spring", "sprout", "spun", "spy", "square", "squeeze",
  "squid", "squirrel", "stab", "stable", "stack", "staff", "stage", "stain", "stair", "stake",
  "stale", "stalk", "stall", "stamp", "stand", "star", "stare", "start", "starve", "state",
  "stay", "steak", "steal", "steam", "steel", "steep", "steer", "stem", "step", "stereo",
  "stick", "stiff", "still", "sting", "stink", "stir", "stock", "stomach", "stone", "stool",
  "stoop", "stop", "store", "storm", "story", "stove", "straight", "strain", "strand", "strange",
  "strap", "straw", "stream", "street", "strength", "stress", "stretch", "strike", "string", "strip",
  "stroke", "strong", "struggle", "student", "stuff", "stumble", "style", "subject", "submit",
  "subtract", "suburb", "succeed", "success", "such", "suck", "sudden", "suffer", "sugar", "suggest",
  "suit", "summer", "sun", "sunny", "sunset", "super", "supply", "support", "suppose", "sure",
  "surface", "surge", "surprise", "surround", "survey", "suspect", "sustain", "swallow", "swamp", "swap",
  "swarm", "swear", "sweat", "sweep", "sweet", "swift", "swim", "swing", "switch", "sword",
  "symbol", "symptom", "syrup", "system", "table", "tackle", "tactics", "tail", "tale", "talent",
  "talk", "tank", "tape", "target", "task", "taste", "tattoo", "tax", "teach", "team", "tear",
  "tease", "technology", "teddy", "teen", "telephone", "telescope", "television", "tell", "temper", "temple",
  "temporary", "tempt", "tenant", "tend", "tender", "tent", "term", "terrible", "territory", "terror",
  "test", "text", "thank", "that", "theme", "then", "theory", "there", "therapy", "thick",
  "thin", "thing", "think", "third", "thirst", "thirteen", "thirty", "this", "thorn", "those",
  "though", "thought", "thousand", "thread", "threat", "three", "thrive", "throw", "thumb", "thunder",
  "ticket", "tide", "tiger", "tight", "tile", "tilt", "timber", "time", "tiny", "tip",
  "tired", "tissue", "title", "toast", "tobacco", "today", "toddler", "toe", "together", "toilet",
  "token", "tomato", "tomb", "tone", "tongue", "tonight", "tool", "tooth", "top", "topic",
  "topple", "torch", "tornado", "tortoise", "toss", "total", "tourist", "toward", "tower", "town",
  "toy", "track", "trade", "tradition", "traffic", "tragedy", "train", "transfer", "trap", "trash",
  "travel", "tray", "treat", "treatment", "tree", "trend", "trial", "tribe", "trick", "trigger",
  "trim", "trip", "trophy", "trouble", "truck", "true", "truly", "trumpet", "trust", "truth",
  "try", "tube", "tuition", "tumble", "tuna", "tunnel", "turkey", "turn", "turtle", "twelve",
  "twenty", "twice", "twin", "twist", "two", "type", "typical", "ugly", "ultimate", "umbrella",
  "un aware", "uncle", "under", "undergo", "understand", "undertake", "undo", "unfair", "unfold", "unhappy",
  "unify", "uniform", "union", "unique", "unit", "unite", "unity", "universal", "universe", "unjust",
  "unknown", "unlike", "unlock", "unlucky", "unnatural", "unreal", "unrest", "unseen", "unstable", "until",
  "unusual", "unwell", "up", "uphold", "upon", "upper", "upset", "upside", "urge", "urgent",
  "use", "used", "useful", "useless", "user", "usual", "usurp", "utopia", "utter", "vacant",
  "vacation", "vague", "vain", "valiant", "valid", "valley", "valuable", "value", "vampire", "van",
  "vanish", "vase", "vast", "vault", "veil", "vein", "velocity", "velvet", "vengeance", "vent",
  "venture", "verdict", "version", "very", "vessel", "veteran", "vex", "via", "vibe", "vice",
  "victim", "victory", "video", "view", "village", "villain", "vine", "violate", "violent", "violet",
  "violin", "virgin", "virtual", "virtue", "virus", "visa", "visible", "vision", "visit", "visual",
  "vital", "vivacious", "vivid", "vocal", "vocation", "voice", "void", "volcano", "volume", "volunteer",
  "vote", "vouch", "vow", "vowel", "voyage", "vulture", "wage", "waist", "wait", "wake",
  "walk", "wall", "wallet", "wander", "want", "war", "ward", "warm", "warn", "warrant",
  "warrior", "wash", "waste", "watch", "water", "wave", "wax", "way", "we", "weak",
  "wealth", "weapon", "wear", "weather", "web", "wedding", "week", "weep", "weigh", "weight",
  "welcome", "welfare", "well", "went", "were", "west", "wet", "whale", "what", "wheat",
  "wheel", "when", "where", "which", "while", "whip", "whirl", "whisper", "white", "whole",
  "why", "wicked", "wide", "widow", "wife", "wild", "will", "win", "wind", "window",
  "wine", "wing", "wink", "winner", "winter", "wipe", "wire", "wish", "wit", "witch",
  "with", "withdraw", "wither", "within", "without", "witness", "wolf", "woman", "wonder", "wood",
  "wooden", "wool", "word", "work", "worker", "world", "worm", "worry", "worse", "worship",
  "worst", "worth", "would", "wound", "wrap", "wreck", "wrench", "wrestle", "wriggle", "wring",
  "write", "wrong", "wrought", "yard", "yarn", "yawn", "year", "yearn", "yell", "yellow",
  "yes", "yesterday", "yet", "yield", "yogurt", "yoke", "yolk", "you", "young", "your",
  "youth", "zeal", "zebra", "zero", "zest", "zigzag", "zip", "zoo", "zoom"];



export let med = [
  "AdveNture",
  "Phenomenological Beautiful",
  "Courage",
  "Interdisciplinary diamond",
  "Elephant",
  "Transcendental fountain",
  "Garden",
  "Existential HelicopTer",
  "Island",
  "Nihilistic jungle",
  "Kitchen",
  "Dystopian laptop",
  "Magnet",
  "Utopian notebook",
  "Octopus",
  "Surrealistic pyramid",
  "Quarantine",
  "Kafkaesque reindeer",
  "Strawberry",
  "Orwellian telephone",
  "Golden Umbrella",
  "Hegelian Covid-19 Vaccine",
  "Wildlife",
  "Kantian xylophone",
  "Yesterday",
  "Nietzschean zeppelin",
  "Alligator",
  "Freudian butterfly",
  "Champion",
  "Jungian delicious",
  "Envelope",
  "Marxist friendship",
  "GUitar",
  "Leninist horizon",
  "Imagine",
  "Stalinist jewelry",
  "Kangaroo",
  "Maoist labyrinth",
  "Mountain",
  "Fascist neighborhood",
  "Orchestra",
  "Totalitarian piano",
  "Quest",
  "Authoritarian river",
  "Symphony",
  "Bureaucratic telescope",
  "Universe",
  "Technocratic volcano",
  "Wilderness",
  "Meritocratic yarn",
  "Balloon",
  "Oligarchic crystal",
  "Explore",
  "Plutocratic fantasy",
  "Goldfish",
  "Kleptocratic icebErg",
  "Journey",
  "Theocratic KiTe",
  "Phenomenological",
  "Interdisciplinary",
  "Transcendental",
  "Existential",
  "Nihilistic",
  "Dystopian",
  "Utopian",
  "Surrealistic",
  "Kafkaesque",
  "Orwellian",
  "Hegelian",
  "Kantian",
  "Nietzschean",
  "Freudian",
  "Jungian",
  "Marxist",
  "Leninist",
  "Stalinist",
  "Maoist",
  "Fascist",
  "Totalitarian",
  "Authoritarian",
  "Bureaucratic",
  "Technocratic",
  "Meritocratic",
  "Oligarchic",
  "Plutocratic",
  "Kleptocratic",
  "Theocratic",
  "Autocratic",
  "Dictatorial",
  "Despotic",
  "Tyrannical",
  "Oppressive",
  "Repressive",
  "Exploitative",
  "Manipulative",
  "Deceptive",
  "Dishonest",
  "Corrupt",
  "Criminal",
  "Immoral",
  "Unethical",
  "Amoral",
  "Apathetic",
  "Indifferent",
  "Complacent",
  "Conformist",
  "Conventional",
  "Conservative",
  "Reactionary",
  "Revolutionary",
  "Radical",
  "Extremist",
  "Fanatical",
  "Zealous",
  "Enthusiastic",
  "Passionate",
  "Dedicated",
  "Committed",
  "Devoted",
  "Dogs are Loyal",
  "Patriotic",
  "Nationalistic",
  "Xenophobic",
  "Racist Person",
  "Golang Language",
  "Homophobic",
  "Transphobic",
  "Ableist",
  "Ageist",
  "Classist",
  "Elitist",
  "Snobbish",
  "Pretentious",
  "Condescending",
  "Patronizing",
  "Superior",
  "Inferior",
  "Subordinate",
  "Dominant",
  "Hegemonic",
  "Imperialistic",
  "Colonialistic",
  "Capitalistic",
  "Socialistic",
  "Communistic",
  "Anarchistic",
  "Libertarian",
  "Egalitarian",
  "Humanistic",
  "Rationalistic",
  "Empiricist",
  "Positivistic",
  "Pragmatic",
  "Utilitarian",
  "Deontological",
  "Virtue-ethics",
  "Care-ethics",
  "Existentialist",
  "Absurdist",
  "Nihilist",
  "Pessimist",
  "Optimist",
  "Realist",
  "Idealist",
  "Romantic",
  "Classicist",
  "Modernist",
  "Postmodernist",
  "Structuralist",
  "Poststructuralist",
  "Deconstructionist",
  "Postcolonialist",
  "Feminist",
  "Queer-theorist",
  "Marxist-feminist",
  "Socialist-feminist",
  "Anarcha-feminist",
  "Ecofeminist",
  "Postfeminist",
  "Transfeminist",
  "Intersectionalist", "Falcon", "geyser", "Harmonica", "incense", "Jasmine",
  "kaleidoscope", "Lantern", "monsoon", "Neutron", "oasis", "Penguin",
  "quicksilver", "Radiance", "saffron", "Tapestry", "utopia", "Vortex", "walrus",
  "Xanadu", "yukon", "Zenith", "albatross", "Bonsai", "chameleon", "Daffodil",
  "evergreen", "Firefly", "gazelle", "Hummingbird", "iris", "Jellyfish", "koala",
  "Lavender", "mermaid", "Nightingale", "orchid", "Panda", "quokka", "Rhinoceros",
  "starfish", "Tulip", "urchin", "Vulture", "wombat", "Xerox", "yogurt", "Zebra",
  "archipelago", "Bioluminescence", "chrysalis", "Dewdrop", "equinox", "Fjord",
  "ginkgo", "Halcyon", "iridescent", "Juniper", "krypton ", "Luminous", "mirage",
  "Nirvana", "obelisk", "Phosphorescence", "quasar", "Renaissance", "solstice",
  "Tundra Region", "ultramarine", "Vernal", "wisteria", "Xanthic", "yttrium", "Zircon",
  "Aurora", "borealis", "Cathedral", "dynamite", "Elegy", "flamenco", "Gargoyle",
  "hieroglyph", "Ichthyosaur", "jester", "Kaleidoscope", "lullaby", "Megalith",
  "naiad", "Oceanic", "papillon", "Quandary", "relic", "Sorbet", "tessellation",
  "Umbra", "vesper", "Waltz", "Xenon", "Wonder", "zest", "Abacus", "bouquet",
  "Cascadia", "daisy", "Ecstasy", "flora", "Giggle", "honeybee", "Ivory",
  "jubilee", "Kettle", "lullaby", "Mango", "nougat", "Oceanview", "paprika",
  "Quartzite", "raindrop", "Sapphire", "Binary 0100", "JaVaScRiPt", "GREy", "Pine@pple",
  "xanthosis", "Yogic", "zestful", "Amethyst", "bougainvillea", "Cantaloupe",
  "daffodil", "Emerald", "flamingo", "Giraffe", "hazelnut", "Igloo", "jester",
  "Kaleidoscope", "lapis", "Mango Shake", "Nougat", "Oceanic", "paprika", "Quartz",
  "rainbow", "SaPPhire", "tangerinE", "uNicorn", "viOlet", "Wisteri@", "xantho$is",
  "logic thinkig", "ZestfuL"
];



export let hard = [
  "abnormal appearance",
  "HoStilE AttitudE",
  "engaging discussion",
  "UnliKe otHers",
  "short-lived phenomenon",
  "GrEatlY sUrPrised",
  "highly sociable",
  "crEaTiVe ThInKing",
  "unique person",
  "RELATiVE AsSeSsMENt",
  "changing patterns",
  "VeRy beAutiful",
  "complete change",
  "IntentionAlLy crUeL",
  "sound imitation",
  "GreaT kInDnesS",
  "absolutely necessary",
  "Fun-lOvInG nAtUrE",
  "joyful feeling",
  "CONsTaNt WORRy",
  "all around",
  "hIgHlY IRRitAtinG",
  "original thinking",
  "InTenSe DrEaD",
  "constant motion",
  "GeNtLe wInD",
  "wrong interpretation",
  "forceFuLlY sEpArAtE",
  "complex problem",
  "nOt InClUdEd",
  "gradually deteriorate",
  "wItHoUt wOrRy",
  "city growth",
  "wElL oRgAnIzEd",
  "fIrMlY rEsIsTaNt",
  "completely different",
  "BrIgHtLy hUeD",
  "CreaTiNg wOrDs",
  "deePly CompAsSiOnAtE",
  "overcast sky",
  "GreaTlY perPlEx",
  "ideal example",
  "eAgEr LearNeR",
  "nocturnal w@lker",
  "Am@zing t@ste",
  "not straightforward",
  "wAndeRlUst feeLInG",
  "unfairly biased",
  "BiG dAtA",
  "bEeR mAkInG",
  "extrEmLy AnGrY",
  "ShowInG cOnTeMpT",
  "easIlY sUrReNdEr",
  "CleaRlY vIsIbLe",
  "GeNerousLy GiViNg",
  "mEnTaL dIsArRaY",
  "hIgHlY InTrIcAtE",
  "GrOoS oveRsTaTEmEnT",
  "dEePly emBaRrAsInG",
  "StArK dIfFeReNcE",
  "eXaCtEd prIcE",
  "dEePly soRrOwFuL",
  "dIsHoneSt SpEaKiNg",
  "rEcEnTlY cOiNEd",
  "logIcAl InCoNsIsTaNcY",
  "redAcTed InFoRmAtIoN",
  "optImIsTiC aLlY rEaLiStIc",
  "extEnDeD sPeecH",
  "vIoLeNtLy wInDy", "PhysicAL attendance", "persoNal decision", "dANgerously careless", "welcoming hoSPitality",
  "charmingly RURAL", "zeitgeist cAptured", "make relataBle", "opposing views", "claustrophobia iNDucing", "deep melancholy",
  "stand-in replacement", "polysyllabic term", "widely varied", "stubbornly determined", "illusion-creating device", "lawsuit-prone",
  "authority craving", "excessively loud", "highly intelligent", "20dB is barely audible", "additional amount", "unethical behavior", "secretly concealed", "high regard",
  "wanderlust feeling", "frequently grumble", "I'm highly excited", "protective cover", "openly uNfriendly", "close bond",
  "verbal INSULT", "energetically animated", "money related", "outgoing personality", "serenely calm", "rule breaker", "deceptive act",
  "openly weeping", "constantly shifting", "highly damaging", "difficult manage", "easily frightened", "difficult situation", "intensely luminous",
  "excessive praiser", "shifting allegiance", "difficult to understand", "drastic alteration", "irresistibly attractive boy", "unusual formation", "loud cry", "highest point", "personal sacrifice",
  "guiding fiGure", "@ctively assist", "pessimistic outlook", "unpredictable nature", "extremely precise", "ostentatiously displayed",
  "excessive vanity", "judicial structure", "predetermined fate", "briefly stated", "slowly expiring", "barely noticeable",
  "peacefully tranquil", "deeply knowledgeable", "xenophile tendency", "fast moving air", "obviously true", "noticeably happy",
  "join together", "briefly existing", "diverse blend", "strongly encourage", "excessive pride",
  "dishonest behavior", "cOmpletely ruin", "overZealous believer", "inc@ntation uttered", "calculating device", "extremely noisy", "exact replica",
  "religious study", "gradually disappearing", "body language", "hypochondria suffering",
  "quickly flee", "combat ready", "mentally process", "effervescently happy", "steadily increase", "extremely talkative", "overly theatrical", "financially ruined",
  "disposable item", "noisy disturbance", "itemized inventory", "horrifyingly graphic",
  "subtly mocking", "curative treatment", "difficult choice", "clever retort", "schadenfreude experience", "theatrical performer",
  "seemingly plausible", "exceptionally talented", "xenoglossic ability", "rapidly moving c@r", "clock device",
  "openly hostile", "fully conscious", "potentially dangerous", "producing results", "overly abundant",
  "entirely unstoppable", "potential danger", "easily understood", " sickness suffering", "steadily growing", "partially shaded", "completely pure", "brightly sparkling",
  "completely equal", "take complete control", "thoughtfully considerate", "xenophobia feeling", "far-off distance",
  "eagerly enthusiastic", "excessive flattery", "emotional release", "moving slowly", "shining brightly", "socially adept",
  "funeral toll", "threshold level", "completely ordinary typer", "hardened exterior", "additional weight", "mutual compromise", "angelic nature",
  "greasy texture", "Her unusual behavior", "xenophile tendency", "My strong desire", "educational process", "fortunate event",
  "acknowledge existence", "become acquainted", "great achievement", "exciting adventure", "alligator creature",
  "altruistic nature", "diplomatic representative", "ambiguous meaning", "amplifying device", "data analysis",
  "anticipate event", "software apPlIcAtion", "building architect", "arrangement plan", "performance assessment",
  "assignment task", "social association", "background atmosphere", "breakthrough discovery",
  "breathtaking view", "broadcast transmission", "mathematical calculation", "joyful celebration", "difficult challenges",
  "championship title", "classification system", "collaborative effort", "comfortable feeling", "regulatory compliance",
  "complicated issue", "concentrate effort", "conclusion reached", "conference meeting",
  "connection established", "considerable amount", "construction process", "continuation phase", "contribution made",
  "coordinating effort", "corrective action", "creative thinking", "dedicated effort", "demonstration event",
  "development phase", "distinct difference", "disciplinary action", "discovery made", "documentary film",
  "economical solution", "electric power", "embarrassing situation", "enthusiastic feeling",
  "establishment founded", "evaluation process", "exaggerated statement", "explanation provided", "fantastic experience",
  "foundation laid", "friendship bond", "functional ability", "generational change", "government agency",
  "grateful feeling", "Headquarters location", "identification process", "implementation phase",
  "improvement made", "independent entity", "information provided", "innovative idea", "installation process",
  "intelligent system", "interactive process", "interference issue", "investig@tion conducted", "journalistic reporting",
  "leadership role", "legislative act", "literary work", "Management system", "manipulative behavior",
  "measurement tool", "meditative state", "modification made", "negotiation process", "observational study",
  "organizational structure", "partnership formed", "personality trait", "preparation phase", "presentation made",
  "procrastination habit", "productive output", "professional service", "programming language", "recognition received",
  "refrigeration system", "registration process", "relationship formed", "representative figure", "requirement met",
  "resolution passed", "responsibility taken", "satisfaction felt", "sensitive ISSUE", "significant impact",
  "$implific@tion process", "specification document", "spontaneous reaction", "substantial amount", "superintending role",
  "supervisory control", "synchronization process", "temperature reading", "termination point", "theoretical concept",
  "tourn@ment competition", "transportation system", "understanding gained", "universal principle",
  "unpredictable outcome", "v@lidation process", "verification step", "vocAbulary list", "volunteering effort"
];



export let pro = [
  'Despite the rain, they Continued their journey.',
  'The professor finally P@used for questions',
  'Results were Promising, but MORE tests were needed',
  'The Team celebr@ted finishing AHEAD of schedule',
  'Her QUICK thinking prevented a worse Outcome',
  'The delayed meeting was set for NEXT WEEK',
  'While waiting for the Train, they discussed plans',
  'Though tired, he AGREED to stay longer',
  'Once #decision was M@dE, there was nO turning back',
  'If WE don’t act now, we may miss the Chance',
  'C++ code: cout << "Playing Typing Game" << endl',
  'Artist Refused to Compromise on quality',
  'Call 1-851-792-7240 for immediate help.',
  'If the weather holds, the event will go AHEAD',
  'Though they disagreed, they stayed friends',
  'Please call 1-800-555-1234 for support',
  'Even with a head start, he lost the race',
  'As soon as they left, the storm began',
  'Given the circumstances, his performance was great',
  'Cryptic message: GRQ PEVZL XRL VF 42',
  '|-|ad she waited, she would have caught the train',
  'By the time they arrived, the show started',
  'The issue was too complex for a quick solution',
  'Zozibini Tunzi wore a stunning evening gown.',
  '|-|ad I known, I would have Attended the meeting.',
  'The $ecret code is 5?A*2e$34# today',
  'The well-rehearsed presentation faced technical issues',
  'Once signed, the deal was done',
  'Your @ccount b@L@nce is $123.45',
  'Unquestionably, perplexing enigmas defy cognizance',
  'She finished the r@ce despite leg pain',
  'The CEO announced his retirement',
  'Without a miracle, we’ll miss the deadline',
  'Given the effort, the result w@s impressive',
  'When in the city, they Visited a coffee shop',
  'She couldn’t open the door, despite her efforts',
  'Despite risks, they invested in the venture',
  'Solve for x in 2x + 5 = 11',
  'Though hesitant, |-|e agreEd eventually',
  'Anthropological significance of food rituals',
  'After the meEting, they went to dinner.',
  'E@rly warning PrevEnted greater damage',
  'Ineffable experiences transcend linguistic expression',
  'After Finishing, they took a Bre@k',
  'Despite $trong evidence, he Claimed innocence.',
  'The Phone battery is at 20% & it needs to be charged',
  'Phenomenological exploration of culinary experiences',
  'Formula: m = (y2 - y1) / (x2 - x1)',
  'Culinary entrepreneurship and innovation.',
  'Their plan failed despite best efforts',
  'Had she known, S|-|e would’ve bought it sooner',
  'The surprise decision was Long-Awaited',
  'After the policy ch@nge, satisfaction improved',
  'My DAILY STEP GOAL is 10,O0O steps BY midNight',
  'The famous formula is E=mc^2 indeed',
  'Though the $ituation looked bad, they stayed hopeful',
  'The initially Doubted prOject succeeded',
  'Though the we@ther was bad, the #event $uCCeeded',
  'If conditions |-|old, the launch will go ahead',
  'Had she studied harder, she’d have passed easily',
  'Esoteric hermeneutics reveal hidden meanings',
  'They finished the Complex task early',
  'In the ciTy, he visits his favorite bookstore',
  'Though risky, they Proceeded with the plan',
  'After the results, they celebrated',
  'Given the effort, the TEAM did great',
  'Had you told me earlier, I could’ve helped',
  'Though tired, the team stayed motivated',
  'Multidimensional theories perplex even scholars.',
  'Though costly, they deemed it worth it',
  'The Anticipated Announcement Shocked Many',
  'Syllogistic reasoning often confounds the untrained',
  'At sunrise, they began the #hike.',
  'They pushed through challenges to finish',
  'Once repairs finished, the building reopened',
  '|-|@d I known, I Would have applied.',
  'Minecraft is a popular $@ndbox game...',
  'The package weighs 5 kg and costs $15 to ship',
  'She always visited old friends when home',
  'it was late, so they postponed the meeting.',
  'Meet me at 3:45 PM sharp today.',
  'Early setbacks didn’t stop success',
  'Dirt Rally 2.0 has challenging gameplay',
  'their prep@ration Changed t#e outcome',
  'The Long-st@nding Policy was updated',
  'Utilize #Instagram fe@tures for FOOD business Growth',
  'After the deadline, NO submissions were accepted',
  'Despite delays, the Project $ucceeded',
  'follow THE instructions for @n easier task',
  'The Decision was cONtroversial BUT right',
  'on free weekends, thEy went C@mping',
  'Given the TIME, tHe work wa$ impressive',
  'though tired, tHeY worked until it w@s done'
];
